### ISSUE TITLE
Rooms to share files even across different networks

### ISSUE THREAD

**Issue by opusonline** [RobinLinus/snapdrop#89] opened 2019-08-15 10:57 UTC
This tool is awesome! Not only its code is fantastic, it even works without trackers and ads. Thank you for that!

One thing I miss sorely is to share files across different networks. I know that online tools are using rooms to achieve this.

So it would be a very nice addition to Snapdrop if it would allow to create a room where all members can even join from different networks.

I've already tested it and so I can say it is possible and would work nicely (See screenshot).

Do you have any concerns or do you agree?

<img width="1392" alt="Screenshot 2019-08-15 at 12 49 22" src="https://user-images.githubusercontent.com/484618/63090573-04cdbf80-bf5c-11e9-889e-c3588d6bea12.png">

**Comment by morgankevinj** [comment] 2019-09-19 16:59
There is another open source app that has this feature:
https://github.com/cowbell/sharedrop

**Comment by Nover2** [comment] 2019-12-20 13:52
It's great. How did you achieve it? I don't know much about node.js.

**Comment by opusonline** [comment] 2019-12-22 12:26
@Nover2 Have a look at https://github.com/RobinLinus/snapdrop/blob/894824eb19708c5950c9076b2c4f50b489b2d4f0/server/index.js#L60. There you'll see that Snapdrop groups users (peers) by their IP address. This is great to start. To achieve rooms across different networks you need to update the app and let the frontend/backend create valid unique room id's that are added to the URL so that the URL can be shared and users using the same URL are sharing the same room no matter in which network they are.

**Comment by Nover2** [comment] 2019-12-22 14:55
@opusonline 
Maybe it is difficult for me. The app is lastest version, but I can't understand how to create valid unique room id in frontend and backend. Maybe I need detailed docs.

**Comment by opusonline** [comment] 2019-12-22 21:47
@Nover2 
Sorry, now I see your problem. Unfortunately you have to be able to code updates and implement the feature on your own. It is currently not built in (this is the reason why this thread exists).

**Comment by Nover2** [comment] 2020-02-02 17:10
@opusonline 
Take the liberty to ask if it is possible to show the code that implements this feature? Is it just a matter of making changes to `index.html`? I think this is an opportunity for me to learn.

**Comment by opusonline** [comment] 2020-02-03 06:31
@Nover2 
Sorry, this is not just a matter of making changes to `index.html`. You would have to adjust the server side and add new elements on the frontend. You really already need profound programming skills to achieve this.

**Comment by lrq3000** [comment] 2020-05-25 03:40
@opusonline maybe you can make a PR out of your change? This may help the developers merge in this feature faster.

**Comment by RobinLinus** [comment] 2020-07-14 19:36
Duplicate of #144

**Closed by RobinLinus** 2020-07-14 19:36 UTC
