### ISSUE TITLE
It isn't running I don't know why but any browser isn't giving it acess to run through

### ISSUE THREAD

**Issue by shivam971768** [RobinLinus/snapdrop#317] opened 2021-06-11 11:19 UTC

**Comment by shivam971768** [comment] 2021-06-11 11:20
website certificate has been revoked

**Comment by Bellisario** [comment] 2021-06-11 14:51
Try with my [node-snapdrop](https://github.com/Bellisario/node-snapdrop) project site (it's the same as the original, but it uses only nodejs):
https://node-snapdrop.herokuapp.com/

**Comment by fm-sys** [comment] 2021-06-11 15:52
Interesting though: for me it is working without problems. So maybe device or geo speciffic?

![Screenshot_20210611_174921_org mozilla firefox_copy_540x1170](https://user-images.githubusercontent.com/64581222/121713870-9917f780-cadd-11eb-8a3e-8021de5f6c0e.jpg)

BTW, duplicate of #316

**Closed** 2021-06-11 20:13 UTC
