### ISSUE TITLE
Allow alias for self

### ISSUE THREAD

**Issue by opusonline** [RobinLinus/snapdrop#90] opened 2019-08-15 11:07 UTC
Hi. I love using your tool! But we've noticed that in a room with many users having the same type of device and OS, it is nearly impossible to distinguish and figure out who is the item related to.

A nice addition in my opinion would be to allow to enter an alias for the own device, just optionally. Then instead of "iOS iPhone" it would say "Henry&lt;br/&gt;&lt;small&gt;&lt;i&gt;(iOS iPhone)&lt;/i&gt;&lt;/small&gt;".

**Comment by jmichael2497** [comment] 2020-01-26 00:51
Duplicate of #69

**Closed** 2020-02-23 23:40 UTC
