### ISSUE TITLE
Down?

### ISSUE THREAD

**Issue by imh1kiko** [RobinLinus/snapdrop#480] opened 2022-08-10 13:31 UTC
Both laptop ("unable to connect") and phone ("connection lost") are timing out.

**Comment by Bellisario** [comment] 2022-08-10 13:33
Duplicate of #474.

**Comment by Bellisario** [comment] 2022-08-10 13:34
Seems to be down also for me...

**Comment by imh1kiko** [comment] 2022-08-10 14:30
Seems fine for now.

**Comment by deplorable76** [comment] 2022-08-12 12:25
unable to connect, site down?

**Comment by Bellisario** [comment] 2022-08-12 13:47
Seems to be up now...

**Comment by asadm** [comment] 2022-08-16 19:12
It's down again.
I have put up a mirror that I plan to maintain and improve: https://airdope.io/

**Comment by jimmy6DOF** [comment] 2022-08-23 19:11
> It's down again. I have put up a mirror that I plan to maintain and improve: https://airdope.io/

just a quick note that discovery is not working for me mobile to pc but great idea and good way to support the app and Robin

**Comment by Ein-Tim** [comment] 2022-08-25 18:19
Currently I don't encounter any problems accessing https://snapdrop.net.

Could you please check if the problem is resolved @imh1kiko?

**Closed** 2022-08-26 11:53 UTC
