### ISSUE TITLE
iOS deosn't work

### ISSUE THREAD

**Issue by HenryTheX** [RobinLinus/snapdrop#61] opened 2018-10-09 10:34 UTC
iOS 12 default safari doesnt work.
When receiving file it pop up a new tab and showing resource blob error

I tried turn on or off al options in iOS system settings including all content blockers cross website tracking and advance options none of them would make the snapdrop work on iphone

I also tried downloading chrome on iOS 12 doesnt work either. always throw new tab showing blob resource error. I tried in different iPhone xs max same same error

**Comment by frol** [comment] 2018-10-09 11:09
+1. It was reported as #59 and closed without a resolution.

**Comment by RobinLinus** [comment] 2018-10-09 13:50
Should be fixed. Does it work for you?
@frol sorry I tested with iOS 11 and couldn't reproduce the bug

**Comment by HenryTheX** [comment] 2018-10-09 13:55
It doesn't work with any of my i devices with iOS 12 exactly the same blob error always

**Comment by HenryTheX** [comment] 2018-10-09 13:55
can anyone fix this with iOS 12?

**Comment by RobinLinus** [comment] 2018-10-09 13:59
I just pushed a fix. Still doesn't work for you?

**Comment by HenryTheX** [comment] 2018-10-09 16:49
Hi it doesn't work on macOS Mojave Safari. The page stopped responding like dead, after 5 seconds of loading

**Comment by RobinLinus** [comment] 2018-10-09 21:08
> Hi just tested, same issue blob error on my iOS 12.0.1 I've iPhone XS Max
Thanks for testing! That's strange though. Could you try to empty your cache? 

> Hi it doesn't work on macOS Mojave Safari. The page stopped responding like dead, after 5 seconds of loading
I refactored the deprecated WebRTC APIs. Can you confirm it works now on macOS Mojave Safari?

**Comment by HenryTheX** [comment] 2018-10-09 23:58
Hi Robin,

I've just empty the website data on iPhone. And the website works! iPhone XS Max official iOS 12.0.1
Here is the few test result :
1. open the link in default Safari web browser: no more blob error, sending picture or pdf will open on the same tab displaying the file immediately after receiving it. So picture on the same tab and PDF file on the same tab. The bad result is can only send 1 file at a time. Because after receiving first file, the snapdrop website is closed and displaying the first attachment on the same tab so the device is disconnected and disappeared from the other device.

**Comment by HenryTheX** [comment] 2018-10-10 00:00
2. after adding the website (snapdrop.net) to iOS home screen (many people would do for a quick access), the file transfer does NOT work when launching from the home screen shortcut. The behaviour is: after recipient iPhone clicked download, nothing happens but send screen still shows transfer completed.

**Comment by HenryTheX** [comment] 2018-10-10 00:03
3. I also tried the website snapdrop.net on iOS Chrome latest built 59. Does NOT work on Chrome iOS. Even Chrome has the same webkit engine as Safari on iPhone. The website stop responding complete after 3 seconds of loading. That is disappointing.

**Comment by HenryTheX** [comment] 2018-10-10 00:11
It would be great if the following can be fixed: 1. adding snapdrop to iOS home screen and launch from home screen instead of typing web address from safari browser icon; 2. receiving multiple file/pdf/files at the same time, like all the other platforms; 3. doesn't works in Chrome iOS.

**Comment by HenryTheX** [comment] 2018-10-10 00:17
Just tested the macOS Mojave Safari it now works perfectly as expected. Thanks very much.

**Comment by frol** [comment] 2018-10-10 07:07
I confirm @HenryTheX findings (iOS 12.1 Beta 2 (Safari works fine now, but it seems that something is going wrong with other browsers))

**Comment by RobinLinus** [comment] 2018-10-10 12:53
> adding snapdrop to iOS home screen and launch from home screen instead of typing web address from safari browser icon;

Should be fixed. 

I opened separate issues for the other two bugs

**Closed by RobinLinus** 2018-10-10 12:53 UTC
