### ISSUE TITLE
devices not showing in local setup

### ISSUE THREAD

**Issue by shubham-715** [RobinLinus/snapdrop#54] opened 2017-11-07 05:16 UTC
Dear Team, I have compiled the snadrop code with dependencies in Ubuntu 14 and 16 both. But after starting the 'gulp serve' command and entering the localhost:5000 in a web browser in all devices which is in the same network, the devices are not showing in UI, so not able to start the transfer among these devices. Please help me with this or I am skipping any steps.

**Comment by fabrixxm** [comment] 2017-11-08 10:09
> - run gulp serve
> - In a second shell run node index.js

**Comment by RobinLinus** [comment] 2018-10-10 12:56
Duplicate of #40

**Closed by RobinLinus** 2018-10-10 12:56 UTC
