### ISSUE TITLE
[Question] Using SnapDrop on office or public Cafe wifi.

### ISSUE THREAD

**Issue by themegabyte** [RobinLinus/snapdrop#426] opened 2022-03-29 07:14 UTC
hey all, 

Just checking if snapdrop is safe to use on public networks and if lets say two devices are involved in a file transfer and if a malicious file can be pushed down the WEBRTC socket to either the phone or the laptop?

Just want to be on the safe side because I depend on it a lot between my phone and my laptop.

Thanks and regards.

**Comment by Bellisario** [comment] 2022-03-29 12:28
@themegabyte, Snapdrop is made everyone can discover each other using on the same network and to prevent "malicious" content while using it you just need to prevent file download after its transfer.
The problem is only that you can't really prevent the file transfer, but only download, so, if you don't want receive the transfer, too, you are forced to close the page.
All this should not be considered as not secure because, just to explain me, if you use Apple AirDrop (whose Snapdrop is inspired) there isn't a really way to prevent file receive but only download, to prevent receive you should disable AirDrop totally (like closing Snapdrop).

**Comment by RobinLinus** [comment] 2022-03-29 12:35
@Bellisario is right. Snapdrop cannot prevent malicious users on your network from sending you unsolicited files. So, if in doubt, do not use Snapdrop on a public WiFi.

**Closed by RobinLinus** 2022-03-29 12:35 UTC
