### ISSUE TITLE
Cant Change my Device name

### ISSUE THREAD

**Issue by Tobitec** [RobinLinus/snapdrop#94] opened 2019-10-22 10:44 UTC
I was wondering if there was a way to change your device name so I can see what exact device I want to share to.

**Comment by winuxue** [comment] 2019-11-21 19:04
an idea can be like this, at the bottom:
https://onedoes.github.io/snapdrop/

**Comment by jmichael2497** [comment] 2020-01-26 00:53
Duplicate of #69 
and
Duplicate of #90

**Comment by wanderseeme** [comment] 2020-02-05 08:05
Yeah if SnapDrop can change device names it will be perfect!

**Comment by picknassaro** [comment] 2020-02-13 22:20
+1 for adding the ability to name my device in the Snapdrop interface. The default should also grab the name of my phone or computer from the device’s settings

**Comment by jmichael2497** [comment] 2020-02-16 20:14
@wanderseeme and @picknassaro 

it looks like you may be new to how https://guides.github.com/features/issues are supposed to be used.

first, since this is marked as a duplicate of other issues... you should use those other issues instead.

second, instead of *commenting* with "+1" and sending unnecessary notifications to everyone in whatever issue... that is what the little smiley face react button is for.

(this is similar to other sites having up/down vote and not commenting unless you have something useful to add, so as not to bother the devs from doing something productive)

hope that helps, welcome to github.

**Comment by DJCrashdummy** [comment] 2020-03-01 20:05
additionally the `+1` resp. `:thumbsup:` reaction at the initial post helps to prioritize the requested issues (have a look at the sorting options of issues)... so if you are writing messages, you just annoy a bunch of people and don't even push the issue as a simple `+1` reaction would do. :wink:

**Comment by PaulSzymanski** [comment] 2020-07-13 12:40
Resolved by https://github.com/RobinLinus/snapdrop/pull/91

**Closed by PaulSzymanski** 2020-07-13 12:40 UTC

**Comment by DJCrashdummy** [comment] 2020-07-14 10:55
@PaulSzymanski i'm not sure if this issue can be considered as solved... because as far as i've seen, you still can't rename your device/name. :thinking:

**Comment by RobinLinus** [comment] 2020-07-14 19:34
> @PaulSzymanski i'm not sure if this issue can be considered as solved... because as far as i've seen, you still can't rename your device/name. 🤔

Is there are strong reason to be able to *rename* a device? Otherwise, we'd stick with random names for the sake of simplicity.

**Comment by pplanch** [comment] 2021-09-08 14:25
Not sure if still possible to add to this thread. One reason for being able to rename (or at least have Snapdrop pull in the device name) is that unless you’re in the possibility to explicitly notify your destinee about your nickname, there’s no way way for them to know who is sending them a file …

**Comment by PhilDevProg** [comment] 2023-02-05 18:56
@RobinLinus If you're in a school and multiple teachers want to send files to their students at the same time (although in different rooms), they don't know which students belong to them and which students should receive the file and asking for the nicknames of 30 students is not a good solution.

**Comment by dontberude21another** [comment] 2024-01-20 23:07
just a refresh button would be nice :)
but @PhilDevProg has a good point too

**Comment by zhuanghaotao** [comment] 2024-01-20 23:08
这是来自ZHNG-Haotiu邮箱自动回复。
