### ISSUE TITLE
Connection lost. Retry in 5 seconds... message

### ISSUE THREAD

**Issue by bluenevus** [RobinLinus/snapdrop#73] opened 2019-01-21 19:26 UTC
I get a constant "Connection lost. Retry in 5 seconds..."

Here is the output

 "GET /scripts/ui.js HTTP/1.1" 200 -
code 404, message File not found
 "GET /server/webrtc HTTP/1.1" 404 -
"GET /sounds/blop.mp3 HTTP/1.1" 200 -
code 404, message File not found
"GET /server/webrtc HTTP/1.1" 404 -
code 404, message File not found
"GET /server/webrtc HTTP/1.1" 404 -

I have it setup on centos with nginx.  can't find the files it is looking for above on server

**Comment by bluenevus** [comment] 2019-01-29 15:05
please

**Comment by bmcgonag** [comment] 2020-02-05 02:03
Can I ask, was this resolved, I'm seeing the same message on Ubuntu 19.10 with Chromium browser.

**Comment by bmcgonag** [comment] 2020-02-05 13:36
Logging using Chromium on Ubuntu 19.10 for this message on my terminal:

```
nginx_1  | 2020/02/05 13:35:07 [error] 7#7: *33 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "GET /server/webrtc HTTP/1.1", upstream: "http://172.18.0.3:3000/server/webrtc", host: "localhost:8080"
nginx_1  | 2020/02/05 13:35:07 [error] 7#7: *33 open() "/usr/share/nginx/html/50x.html" failed (2: No such file or directory), client: 172.18.0.1, server: , request: "GET /server/webrtc HTTP/1.1", upstream: "http://172.18.0.3:3000/server/webrtc", host: "localhost:8080"
nginx_1  | 172.18.0.1 - - [05/Feb/2020:13:35:07 +0000] "GET /server/webrtc HTTP/1.1" 404 555 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/79.0.3945.130 Chrome/79.0.3945.130 Safari/537.36" "-"
```

**Comment by ask870** [comment] 2020-05-01 03:09
I got the same error messages.  server: ubuntu-server: Ubuntu 18.04.4

**Comment by FaZeFla5H** [comment] 2020-06-16 17:21
yeah no clue why is that happening

**Comment by Wawuschel** [comment] 2020-06-16 17:55
the same here... 🙁
![Gif-Animation 2020-06-16 19-41-55](https://user-images.githubusercontent.com/8377249/84810201-495a3980-b00b-11ea-9960-35847921ac51.gif)

**Comment by swopnilnep** [comment] 2020-06-17 06:21
Getting the same error on Firefox 78.0 on MacOS 10.15. 
Console output is `Firefox can’t establish a connection to the server at wss://snapdrop.net/server/webrtc.`

**Comment by tenebrism** [comment] 2020-06-17 20:31
Also getting it on all of my devices and browsers. MacOS 10.15.6 with Chrome and Safari. iPhone with iOS 13.6 using Chrome and Safari, Pixel 3 with Android 10 using Chrome and Firefox.

**Comment by simonejgreen** [comment] 2020-06-18 00:34
Ughhh it’s happening to me too! Maybe a glitch in the system? I use this because gmail makes my vids and pics choppy

**Comment by swopnilnep** [comment] 2020-06-18 00:51
So far, I've tried different devices with varying user agents and empty cache on each. It shows the same error for all of the cases that I tried. I can't tell the reason but I am guessing it it is irrelevant to the device or browser. Maybe more related to the network itself?

**Comment by wyudong** [comment] 2020-06-18 01:47
maybe server is down

**Comment by Dekkerb** [comment] 2020-06-18 09:08
Problem here too. Server down?

**Comment by zxjack** [comment] 2020-06-18 12:41
Problem here too. Server down?

**Comment by Terryss95** [comment] 2020-06-18 22:51
Same issue here, ever happened before after months of using this app almost everyday.
Could you please fix this issue? I don't really have an alternative to send files locally between ios and my pc.

Thank you.

**Comment by swopnilnep** [comment] 2020-06-18 22:56
While I prefer using Snapdrop, [Sharedrop](https://www.sharedrop.io/) does the same thing with Ember. You can use that until the problem is fixed. 

> Same issue here, never happened before after months of using this app almost everyday.
> Could you please fix this issue? I don't really have an alternative to send files locally between ios and my pc.
> 
> Thank you.

**Comment by Wawuschel** [comment] 2020-06-19 08:35
Snapdrop.io isn’t the same - I can’t send text between the devices, like a url.

**Comment by iFreilicht** [comment] 2020-06-19 10:14
Same here, tried it on two phones, and iPad and two PCs. No game :(

**Comment by linwea** [comment] 2020-06-22 21:06
same error  centos7

**Comment by jeanphillippe** [comment] 2020-06-26 20:17
Same error, Win 10 and Android 9

**Comment by jaredzimmerman** [comment] 2020-06-26 20:54
Due to this issue (now happening 100% of the time) this has become completely unusable for me.

**Comment by ChayimEliazer** [comment] 2020-06-27 08:06
Same problem.

**Comment by PaulSzymanski** [comment] 2020-06-27 20:34
Hey, sorry folks. The server constantly threw errors and restarted for some months now. However, on 16th of June this happened in fast succession so that systemd decided to not further try to restart the service.

If someone has an idea what might cause the trouble please share. Unfortunately, I currently don't have the time to investigate. Here is the trace:
`events.js:183
throw er; // Unhandled 'error' event
^
RangeError: Invalid WebSocket frame: RSV1 must be clear
at Receiver.getInfo (/ci/snapdrop/server/node_modules/ws/lib/receiver.js:167:14)
at Receiver.startLoop (/ci/snapdrop/server/node_modules/ws/lib/receiver.js:121:22)
at Receiver._write (/ci/snapdrop/server/node_modules/ws/lib/receiver.js:69:10)
at doWrite (_stream_writable.js:396:12)
at writeOrBuffer (_stream_writable.js:382:5)
at Receiver.Writable.write (_stream_writable.js:290:11)
at Socket.socketOnData (/ci/snapdrop/server/node_modules/ws/lib/websocket.js:794:35)
at emitOne (events.js:116:13)`

**Comment by ChayimEliazer** [comment] 2020-06-27 20:38
It's working now.

**Comment by PaulSzymanski** [comment] 2020-06-27 20:40
Yes, its working for now but it will break again. Usually the service should just be restarted in that case. If this happens in the middle while someone is transferring a large file this could be annoying at least.

**Comment by willstott101** [comment] 2020-06-27 22:02
Are transfers cancelled when the server goes down? If a webrtc connection is running the clients could just keep running?

**Comment by simonejgreen** [comment] 2020-06-27 22:03
guys can you try again? it’s working for me right now!

**Comment by willstott101** [comment] 2020-06-27 22:03
There are systemd options to allow infinite restart, or at least to up the maximum restart burt rate. It might be worth setting those, if you haven't already.

**Comment by PaulSzymanski** [comment] 2020-06-27 22:27
@willstott101 Files are sent in chunks. The websocket server is required to send meta information about the chunks being transferred.
I have disabled the restart rate limiting. Thanks for the tip :)

**Comment by nashosted** [comment] 2020-09-15 17:22
If you are using Nginx Proxy Manager you must enable Websockets Support in the proxy host.

**Comment by vihu** [comment] 2020-09-24 06:33
> If you are using Nginx Proxy Manager you must enable Websockets Support in the proxy host.

```
server {
	server_name my.domain.com;

	location / {
		proxy_pass http://localhost:8000;
	}

    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/my.domain.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/my.domain.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = my.domain.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


	server_name my.domain.com;
    listen 80;
    return 404; # managed by Certbot


}
```

@nashosted could you expand on that please? That's my basic nginx conf for snapdrop, what stanza am I missing for websocket?

**Comment by najtin** [comment] 2020-09-24 10:25
the https server part is missing some statements. This is from the docker in this repo, compare it to your config and add the missing statements: 
```
server {
    listen       443 ssl http2;
    ssl_certificate /etc/ssl/certs/snapdrop-dev.crt;
    ssl_certificate_key /etc/ssl/certs/snapdrop-dev.key;

    #server_name  ;

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    expires epoch;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    location /server {
        proxy_connect_timeout 300;
        proxy_pass http://node:3000;
        proxy_set_header Connection "upgrade";
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Forwarded-for $remote_addr;
    }

    location /ca.crt {
        alias /etc/ssl/certs/snapdropCA.crt;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}
```

what you need are the Connection upgrade, Upgrade, and X-Forwareded-for directives

**Comment by vihu** [comment] 2020-09-24 17:35
> the https server part is missing some statements. This is from the docker in this repo, compare it to your config and add the missing statements:
> 
> ```
> server {
>     listen       443 ssl http2;
>     ssl_certificate /etc/ssl/certs/snapdrop-dev.crt;
>     ssl_certificate_key /etc/ssl/certs/snapdrop-dev.key;
> 
>     #server_name  ;
> 
>     #charset koi8-r;
>     #access_log  /var/log/nginx/host.access.log  main;
> 
>     expires epoch;
> 
>     location / {
>         root   /usr/share/nginx/html;
>         index  index.html index.htm;
>     }
> 
>     location /server {
>         proxy_connect_timeout 300;
>         proxy_pass http://node:3000;
>         proxy_set_header Connection "upgrade";
>         proxy_set_header Upgrade $http_upgrade;
>         proxy_set_header X-Forwarded-for $remote_addr;
>     }
> 
>     location /ca.crt {
>         alias /etc/ssl/certs/snapdropCA.crt;
>     }
> 
>     #error_page  404              /404.html;
> 
>     # redirect server error pages to the static page /50x.html
>     #
>     error_page   500 502 503 504  /50x.html;
>     location = /50x.html {
>         root   /usr/share/nginx/html;
>     }
> }
> ```
> 
> what you need are the Connection upgrade, Upgrade, and X-Forwareded-for directives

Thanks @najtin , that was it :+1:

**Closed** 2020-12-16 05:34 UTC
