### ISSUE TITLE
Snapdrop progress stuck for files over 100MB

### ISSUE THREAD

**Issue by rilysh** [RobinLinus/snapdrop#612] opened 2023-08-30 13:55 UTC
When transferring between computer and phone, Snapdrop happily uploads to 50 to 70 MB, and then suddenly transfer progress gets stopped. I tried a couple of times but got the same results. I also tried file under 70MB and it worked perfectly fine. And it seems only for large files this issue persists.

**Comment by Bellisario** [comment] 2023-08-30 21:02
Seems duplicate of #231.

@rilysh, this is a common problem of Snapdrop.\
Since file data downloading is cached locally and then saved on your device storage after data transfer is completed, browsers will block a cache storage if it's too large.

The maximum size you can possibly transfer is about 1GB, but it could vary depending on your device: for example, probably because you're using a phone, your cache size is even smaller and you stuck at 70MB.

Currently there is no solution for this issue as Snapdrop is a web-app and browsers does not allow a greater cache storage.

**Comment by rilysh** [comment] 2023-09-18 19:44
I see, that make sense now, thank you @Bellisario for your explanation!

**Comment by zhuanghaotao** [comment] 2023-09-18 19:45
这是来自ZHNG-Haotiu邮箱自动回复。

**Closed** 2023-09-18 19:45 UTC
