### ISSUE TITLE
Connection lost. Retry in 5 seconds... 

### ISSUE THREAD

**Issue by sechip** [RobinLinus/snapdrop#145] opened 2020-06-18 15:25 UTC
It worked perfectly, I used it constantly in my days but a week ago I stopped working, I was so happy that I thought of donating to keep it growing as it is the most intuitive I have found

**Comment by flecca** [comment] 2020-06-18 20:20
I too have this issue, i discovered snapdrop and created shortcuts on all my deviced in the event that i would need it. When i needed it, it wouldnt work, just saying what you said every 5 seconds and never resolving. Tried on multiple networks with no resolution

**Comment by swopnilnep** [comment] 2020-06-18 23:05
Duplicate of #73

**Comment by flecca** [comment] 2020-06-19 01:02
> Duplicate of #73 

It doesnt seem like anything was fixed in that thread though
I signed up with github just for this particular problem so lmk if im missing anything here

**Comment by branflakes104** [comment] 2020-06-19 14:23
I am also having this issue.  Since it is happening on all my devices on all platforms, I tend to think it's a setting on my internal network.  I just don't know where to start.  Blocked Port?

**Comment by rbdunne** [comment] 2020-06-19 15:56
I just started having this problem. (On both my Chromebook and Samsung Note 9.) Worked fine a few weeks ago. I'm guessing a chrome update broke it?

**Comment by flecca** [comment] 2020-06-19 16:02
> I just started having this problem. (On both my Chromebook and Samsung Note 9.) Worked fine a few weeks ago. I'm guessing a chrome update broke it?

I dont think chrome is the issue, I was experiencing this between Safari on IOS and Firefox on Windows

**Comment by swopnilnep** [comment] 2020-06-19 19:15
> It doesnt seem like anything was fixed in that thread though
> I signed up with github just for this particular problem so lmk if im missing anything here

Yes, however usually when an issue is a duplicate, the original one is used. It is helpful other users who have the problem when the discussion is in one place and there aren't multiple groups trying to solve the same problem.

Hope that helps.

**Comment by flecca** [comment] 2020-06-19 19:19
> > It doesnt seem like anything was fixed in that thread though
> 
> > I signed up with github just for this particular problem so lmk if im missing anything here
> 
> 
> 
> Yes, however usually when an issue is a duplicate, the original one is used. It is helpful other users who have the problem when the discussion is in one place and there aren't multiple groups trying to solve the same problem.
> 
> 
> 
> Hope that helps.

Ah i see, i guess the OP for thus post should delete this one and comment on original instead

**Comment by abugamel** [comment] 2020-06-20 03:07
Same issue here 

Anyone can help please?

**Comment by 24seconds** [comment] 2020-06-21 08:39
I looked up console and it says  
> network.js:16 WebSocket connection to 'wss://snapdrop.net/server/webrtc' failed: Error during WebSocket handshake: Unexpected response code: 404

maybe signaling server is dead?

**Comment by sechip** [comment] 2020-06-21 13:55
> Busqué la consola y dice
> 
> > error en la conexión web network.js:16 a 'wss://snapdrop.net/server/webrtc': Error durante el protocolo de enlace de WebSocket: Código de respuesta inesperado: 404
> 
> tal vez el servidor de señalización está muerto?

It's most likely

**Comment by zszen** [comment] 2020-06-22 09:15
Same issue

**Comment by swarupmondal** [comment] 2020-06-22 19:54
@RobinLinus Can you please solve the issue?

**Comment by mudassirzulfiqar** [comment] 2020-06-22 20:55
Having same issue.

**Comment by linwea** [comment] 2020-06-22 21:11
WebSocket connection to 'ws://localhost:8080/server/webrtc' failed: Error during WebSocket handshake: Unexpected response code: 404

**Comment by willstott101** [comment] 2020-06-23 11:31
#73 is a support request for someone self-hosting snapdrop. This issue is specifically about the production instance so I wouldn't call it a dupe.

**Comment by benmurrell** [comment] 2020-06-24 19:50
I am seeing the same issue as others above on the production instance at https://snapdrop.net/. 

In the browser, I see "Connection lost. Retry in 5 seconds..."

In the debug console, I see "WebSocket connection to 'wss://snapdrop.net/server/webrtc' failed: Error during WebSocket handshake: Unexpected response code: 404."

**Comment by DavidM974** [comment] 2020-06-26 05:12
Same issue for me on windows and ios and android ...

**Comment by PaulSzymanski** [comment] 2020-06-27 21:00
Hey folks! Sorry for the delay. The service turned into failed state because it was constantly restarting. I've restarted the service for now but the underlying issue still needs to be fixed. Please look at my comment in the duplicate issue https://github.com/RobinLinus/snapdrop/issues/73#issuecomment-650621029.
I will close this issue as it is a duplicate.

**Closed by PaulSzymanski** 2020-06-27 21:00 UTC

**Comment by nashosted** [comment] 2020-09-15 17:22
If you are using Nginx Proxy Manager you must enable Websockets Support in the proxy host.

**Comment by vintonic** [comment] 2021-03-08 21:54
The service is currently down with the same error message ("connection lost")... could you fix it please? @PaulSzymanski
